### ISSUE TITLE
research the best way to send e-mail and text notifications

### ISSUE THREAD

**Issue by ika-musuko** [ika-musuko/tma#9]
since our application will be sending e-mail and text notifications to the user, this is something that we should look into now. find out the best libraries (external libraries OK) for this and make a test script sending an email and a text message. 

here are some starter links i dug up. figure out the easiest solution
email and text: https://automatetheboringstuff.com/chapter16/
email: https://docs.python.org/3.5/library/email-examples.html
text: https://www.textmagic.com/docs/api/python/

**Comment by ika-musuko** [comment]
```
import textmagic.client

# Use your username and API password to create a client
client = textmagic.client.TextMagicClient('your_username', 'your_api_password')

# Send a message and store its message id
result = client.send("Hello, World!", "1234567890")
message_id = result['message_id'].keys()[0]

# Now you can retrieve the delivery status using the message id
response = client.message_status(message_id)
status = response[message_id]['status']

# Replies to your outgoing messages are delivered to your TextMagic Inbox
# This is how you receive messages from your Inbox
received_messages = client.receive(0)
messages_info = received_messages['messages']
for message_info in messages_info:
  print "%(text)s received from %(from)s" % message_info

# Delete a message from your Inbox
client.delete_reply(message_info['message_id'])

# Get your account balance
balance = client.account()['balance']

# Find the country and cost of a telephone number
response = client.check_number('44123456789')
info = response['44123456789']
country = info['country']
credits = info['price']

```

**Comment by ika-musuko** [comment]
https://github.com/ika-musuko/tma/files/1412248/pdf-2.pdf

**Comment by lucyc426** [comment]
API Key: sjbEMjfNrrglXY4zCFufIw9IPlZ3SA
Username: lucychibukhchyan

**Comment by lucyc426** [comment]
import smtplib

to = 'lucy.chibukhchyan@gmail.com'
gmail_user = 'timemanagamenet131@gmail.com'
gmail_pwd = 'cmpe131f17'
smtpserver = smtplib.SMTP("smtp.gmail.com",587)
smtpserver.ehlo()
smtpserver.starttls()
smtpserver.ehlo
smtpserver.login(gmail_user, gmail_pwd)
header = 'To:' + to + '\n' + 'From: ' + gmail_user + '\n' + 'Subject:testing \n'
print header
msg = header + '\n this is test msg from mkyong.com \n\n'
smtpserver.sendmail(gmail_user, to, msg)
print 'done!'
smtpserver.close()

**Comment by lucyc426** [comment]
TEXT:


import smtplib

# Use sms gateway provided by mobile carrier:
# at&t:     number@mms.att.net
# t-mobile: number@tmomail.net
# verizon:  number@vtext.com
# sprint:   number@page.nextel.com

# Establish a secure session with gmail's outgoing SMTP server using your gmail account
server = smtplib.SMTP( "smtp.gmail.com", 587 )

server.starttls()

server.login( '<gmail_address>', '<gmail_password>' )

# Send text message through SMS gateway of destination number
server.sendmail( '<from>', '<number>@tmomail.net', '<msg>' )

**Comment by lucyc426** [comment]
HOW TO SEND EMAIL'S FROM TMA EMAIL:

`import smtplib

From = 'urmail@gmail.com'  
Recipient  = 'some1else'smail@gamil.com'  
Messege = """From: ur_name <ur_email>
To: <Recipient_email>
Subject: Testing Testing Testing

This is test messege.
Love python and continue loving it.
"""  
 
# Credentials
username = 'ur_email'  
password = 'password'  
  
# mail is being sent :  
server = smtplib.SMTP('smtp.gmail.com:587')  
server.starttls()  
server.login(username,password)  
server.sendmail(From, Recipient, Messege)  
server.quit() `

**Comment by lucyc426** [comment]
`>>> import smtplib
>>> From='timemanagement131@gmail.com'
>>> Recipient='lucy.chibukhchyan@gmail.com'
>>> Message= """From: lucy <timemanagement131@gmail.com>
To: <lucy.chibukhchyan@gmail.com>
Subject: test test test

test message ok bye
"""
>>> username='timemanagement131@gmail.com'
>>> password='cmpe131f17'
>>> server=smtplib.SMTP('smtp.gmail.com:587')
>>> server.starttls()
(220, b'2.0.0 Ready to start TLS')
>>> server.login(username,password)
(235, b'2.7.0 Accepted')
>>> server.sendmail(From, Recipient, Message)
{}
>>> server.quit()
(221, b'2.0.0 closing connection l22sm12190670pfk.45 - gsmtp')
>>> `

**Comment by lucyc426** [comment]
```
>>> import smtplib
>>> From='timemanagement131@gmail.com'
>>> Recipient='lucy.chibukhchyan@gmail.com'
>>> Message= """From: lucy <timemanagement131@gmail.com>
To: <lucy.chibukhchyan@gmail.com>
Subject: test test test

test message ok bye
"""
>>> username='timemanagement131@gmail.com'
>>> password='cmpe131f17'
>>> server=smtplib.SMTP('smtp.gmail.com:587')
>>> server.starttls()
(220, b'2.0.0 Ready to start TLS')
>>> server.login(username,password)
(235, b'2.7.0 Accepted')
>>> server.sendmail(From, Recipient, Message)
{}
>>> server.quit()
(221, b'2.0.0 closing connection l22sm12190670pfk.45 - gsmtp')
>>> 
```

**Comment by lucyc426** [comment]
FINAL CODE: HOW TO SEND EMAIL FROM TMA GMAIL ACCT

```
import smtplib

From = 'timemanagement131@gmail.com'  
Recipient  = 'studentemail@gmail.com'  
Messege = """
From: Time Management Assistant <timemanagement131@gmail.com>
To: <studentemail@gmail.com>
Subject: Testing Testing Testing

This is a test message.

"""  
 
# Credentials
username = 'timemanagement131@gmail.com'  
password = 'cmpe131f17'  
  
# mail is being sent :  
server = smtplib.SMTP('smtp.gmail.com:587')  
server.starttls()  
server.login(username,password)  
server.sendmail(From, Recipient, Messege)  
server.quit() 

```

**Comment by lucyc426** [comment]
TMA gmail account:
timemanagement131@gmail.com
password: cmpe131f17
